name: dl_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0=h6b3803e_1
  - absl-py=2.1.0=py39hca03da5_0
  - appnope=0.1.2=py39hca03da5_1001
  - asttokens=3.0.0=py39hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=openblas
  - brotli-python=1.0.9=py39h313beb8_9
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.2.25=hca03da5_0
  - certifi=2025.4.26=py39hca03da5_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py39hca03da5_0
  - debugpy=1.8.11=py39h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.17.0=py39hca03da5_0
  - freetype=2.13.3=h47d26ad_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py39h5c1b81f_0
  - grpc-cpp=1.48.2=hc60591f_1
  - idna=3.7=py39hca03da5_0
  - importlib-metadata=8.5.0=py39hca03da5_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.15.0=py39hca03da5_0
  - jedi=0.19.2=py39hca03da5_0
  - jinja2=3.1.6=py39hca03da5_0
  - jpeg=9e=h80987f9_3
  - jupyter_client=8.6.3=py39hca03da5_0
  - jupyter_core=5.7.2=py39hca03da5_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libgrpc=1.71.0=h62f6fdd_0
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenblas=0.3.29=hea593b9_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=5.29.3=h9f9f828_0
  - libre2-11=2024.07.02=h313beb8_0
  - libsodium=1.0.18=h1a28f6b_0
  - libtiff=4.7.0=h91aec0a_0
  - libwebp-base=1.3.2=h80987f9_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown=3.8=py39hca03da5_0
  - markupsafe=3.0.2=py39h80987f9_0
  - matplotlib-inline=0.1.6=py39hca03da5_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py39hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py39hca03da5_0
  - networkx=3.2.1=py39hca03da5_0
  - openjpeg=2.5.2=hba36e21_1
  - openssl=3.0.16=h02f6b3c_0
  - packaging=24.2=py39hca03da5_0
  - parso=0.8.4=py39hca03da5_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.1.0=py39h41ba818_1
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.7=py39hca03da5_0
  - prompt-toolkit=3.0.43=py39hca03da5_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - protobuf=5.29.3=py39h514c7bf_0
  - psutil=5.9.0=py39h80987f9_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.19.1=py39hca03da5_0
  - pysocks=1.7.1=py39hca03da5_0
  - python=3.9.20=hb885b13_1
  - python-dateutil=2.9.0post0=py39hca03da5_2
  - python_abi=3.9=2_cp39
  - pytorch=2.4.1=py3.9_0
  - pyyaml=6.0.2=py39h80987f9_0
  - pyzmq=26.2.0=py39h313beb8_0
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.2=h1a28f6b_0
  - setuptools=78.1.1=py39hca03da5_0
  - six=1.17.0=py39hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.3=py39hca03da5_1
  - tensorboard=2.18.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py39ha6e5c4f_1
  - torchaudio=2.4.1=py39_cpu
  - torchvision=0.19.1=py39_cpu
  - traitlets=5.14.3=py39hca03da5_0
  - typing_extensions=4.12.2=py39hca03da5_0
  - urllib3=2.3.0=py39hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=3.1.3=py39hca03da5_0
  - wheel=0.45.1=py39hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.21.0=py39hca03da5_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.4.0
      - alembic==1.16.3
      - anyio==4.6.2.post1
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.17.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - contourpy==1.3.0
      - coreforecast==0.0.16
      - cycler==0.12.1
      - d2l==1.0.3
      - defusedxml==0.7.1
      - dtaidistance==2.3.13
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - fastdtw==0.3.4
      - fastjsonschema==2.20.0
      - fonttools==4.54.1
      - fqdn==1.5.1
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2024.9.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.67.0
      - h11==0.14.0
      - html5lib==1.1
      - httpcore==1.0.6
      - httpx==0.27.2
      - importlib-resources==6.4.5
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpickle==4.0.5
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lightning-utilities==0.14.3
      - llvmlite==0.43.0
      - lxml==5.3.0
      - mako==1.3.10
      - matplotlib==3.7.2
      - mistune==3.0.2
      - msgpack==1.1.1
      - multidict==6.6.3
      - multitasking==0.0.11
      - mxnet==1.6.0
      - narwhals==1.37.1
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - neuralforecast==3.0.2
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.23.5
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - optuna==4.4.0
      - overrides==7.7.0
      - pandas==2.0.3
      - pandas-datareader==0.10.0
      - pandocfilters==1.5.1
      - peewee==3.17.7
      - plotly==6.0.1
      - prometheus-client==0.21.0
      - propcache==0.3.2
      - pyarrow==20.0.0
      - pycocotools==2.0.8
      - pycparser==2.22
      - pyparsing==3.0.9
      - python-graphviz==0.8.4
      - python-json-logger==2.0.7
      - pytorch-lightning==2.5.2
      - pytz==2024.2
      - pyvis==0.3.2
      - qtconsole==5.6.0
      - qtpy==2.4.1
      - ray==2.47.1
      - referencing==0.35.1
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - scikit-learn==1.5.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - shap==0.48.0
      - slicer==0.0.8
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.41
      - tensorboardx==2.6.4
      - terminado==0.18.1
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tk==0.1.0
      - tomli==2.0.2
      - torchmetrics==1.7.4
      - tornado==6.4.1
      - tqdm==4.66.5
      - types-python-dateutil==2.9.0.20241003
      - tzdata==2024.2
      - uri-template==1.3.0
      - utilsforecast==0.2.12
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - yarl==1.20.1
      - yfinance==0.1.87
prefix: /Users/dennisliu/anaconda3/envs/dl_env
